"""empty message

Revision ID: 1669bc217a85
Revises: 35da2dbd4637
Create Date: 2025-04-19 11:01:59.485237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1669bc217a85'
down_revision: Union[str, None] = '35da2dbd4637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text("TIMEZONE( 'utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.yandex_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_token_id'), 'tokens', ['token_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_token_id'), table_name='tokens')
    op.drop_table('tokens')
    # ### end Alembic commands ###
