"""empty message

Revision ID: 512db707f1ea
Revises: ac876dbbf9d9
Create Date: 2025-04-13 17:50:39.720799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512db707f1ea'
down_revision: Union[str, None] = 'ac876dbbf9d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('announcement_id', sa.Integer(), nullable=False))
    op.drop_index('ix_files_annnouncement_id', table_name='files')
    op.create_index(op.f('ix_files_announcement_id'), 'files', ['announcement_id'], unique=False)
    op.drop_constraint('files_annnouncement_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'announcements', ['announcement_id'], ['id'], ondelete='CASCADE')
    op.drop_column('files', 'annnouncement_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('annnouncement_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key('files_annnouncement_id_fkey', 'files', 'announcements', ['annnouncement_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_files_announcement_id'), table_name='files')
    op.create_index('ix_files_annnouncement_id', 'files', ['annnouncement_id'], unique=False)
    op.drop_column('files', 'announcement_id')
    # ### end Alembic commands ###
