"""empty message

Revision ID: 9c1baa128976
Revises: c33c32cfc485
Create Date: 2025-04-19 10:28:46.214987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1baa128976'
down_revision: Union[str, None] = 'c33c32cfc485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('issued_at', sa.DateTime(), server_default=sa.text("TIMEZONE( 'utc', now())"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'issued_at')
    # ### end Alembic commands ###
