"""empty message

Revision ID: ac876dbbf9d9
Revises: 7cf8ad37b968
Create Date: 2025-04-13 13:04:57.744113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac876dbbf9d9'
down_revision: Union[str, None] = '7cf8ad37b968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_1', sa.String(), nullable=True),
    sa.Column('image_2', sa.String(), nullable=True),
    sa.Column('image_3', sa.String(), nullable=True),
    sa.Column('image_4', sa.String(), nullable=True),
    sa.Column('image_5', sa.String(), nullable=True),
    sa.Column('image_6', sa.String(), nullable=True),
    sa.Column('image_7', sa.String(), nullable=True),
    sa.Column('image_8', sa.String(), nullable=True),
    sa.Column('image_9', sa.String(), nullable=True),
    sa.Column('image_10', sa.String(), nullable=True),
    sa.Column('annnouncement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['annnouncement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_annnouncement_id'), 'files', ['annnouncement_id'], unique=False)
    op.alter_column('announcements', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_announcements_category_id'), 'announcements', ['category_id'], unique=False)
    op.drop_constraint('announcements_category_id_fkey', 'announcements', type_='foreignkey')
    op.create_foreign_key(None, 'announcements', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_column('announcements', 'image_10')
    op.drop_column('announcements', 'image_1')
    op.drop_column('announcements', 'image_4')
    op.drop_column('announcements', 'image_2')
    op.drop_column('announcements', 'image_6')
    op.drop_column('announcements', 'image_3')
    op.drop_column('announcements', 'image_5')
    op.drop_column('announcements', 'image_9')
    op.drop_column('announcements', 'image_8')
    op.drop_column('announcements', 'image_7')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('image_7', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('announcements', sa.Column('image_8', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('announcements', sa.Column('image_9', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('announcements', sa.Column('image_5', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('announcements', sa.Column('image_3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('announcements', sa.Column('image_6', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('announcements', sa.Column('image_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('announcements', sa.Column('image_4', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('announcements', sa.Column('image_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('announcements', sa.Column('image_10', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.create_foreign_key('announcements_category_id_fkey', 'announcements', 'categories', ['category_id'], ['id'])
    op.drop_index(op.f('ix_announcements_category_id'), table_name='announcements')
    op.alter_column('announcements', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_files_annnouncement_id'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
