"""empty message

Revision ID: c33c32cfc485
Revises: 2bc85b497c12
Create Date: 2025-04-19 10:19:40.633459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c33c32cfc485'
down_revision: Union[str, None] = '2bc85b497c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('tokens', sa.Column('token_id', sa.String(), nullable=False))
    op.add_column('tokens', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('tokens', sa.Column('is_banned', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_tokens_token_id'), 'tokens', ['token_id'], unique=True)
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['yandex_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_index(op.f('ix_tokens_token_id'), table_name='tokens')
    op.drop_column('tokens', 'is_banned')
    op.drop_column('tokens', 'user_id')
    op.drop_column('tokens', 'token_id')
    op.drop_column('tokens', 'id')
    # ### end Alembic commands ###
