"""empty message

Revision ID: dca3a2a24675
Revises: 512db707f1ea
Create Date: 2025-04-14 10:59:13.025950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca3a2a24675'
down_revision: Union[str, None] = '512db707f1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_files_announcement_id', table_name='files')
    op.drop_table('files')
    op.add_column('announcements', sa.Column('image_1', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('image_2', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('image_3', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('image_4', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('image_5', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('image_6', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('image_7', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('image_8', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('image_9', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('image_10', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'image_10')
    op.drop_column('announcements', 'image_9')
    op.drop_column('announcements', 'image_8')
    op.drop_column('announcements', 'image_7')
    op.drop_column('announcements', 'image_6')
    op.drop_column('announcements', 'image_5')
    op.drop_column('announcements', 'image_4')
    op.drop_column('announcements', 'image_3')
    op.drop_column('announcements', 'image_2')
    op.drop_column('announcements', 'image_1')
    op.create_table('files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_4', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_5', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_6', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_7', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_8', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_9', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_10', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('announcement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], name='files_announcement_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='files_pkey')
    )
    op.create_index('ix_files_announcement_id', 'files', ['announcement_id'], unique=False)
    # ### end Alembic commands ###
